language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install codecov
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: DUT/C6w/Vsb00UAg94jb2g1Ri/Oh0qhgqmlhWwuDbkYeKia8kCc+dzh/zbd3U4vOJ5v2+uy2KUHFl48UmCYx3nWAhU5DrLT07J3ZhxZI2oD83SF8BJQtXa1NaTpqNRw8uDu9fsMwB2y0cMY3Z5oznUHACl5U2QpUwtaayt807Be5hNLPfODNpknSIVZqGtv4ANNVSOuwgJWQxgSM4hv6y92xPC/KkBBhPLPx22A4rLTfPOxu4fWVSSkc+76uV6MtaIf18ZFFrJ1f9KrwNkJ6GNoAmiTS1lueOhBnLG2mJRqVFxWPDzzydIKSLCzI+pAgTJ1szxxKddrTzcf2XO0YjNH5/jHpcqHr3X4a9HPLF/kkVHPQlqOl+Tyciqo9miYcko8aSZ/dSiIhMNtmBk7G+XF4/OsVFN8E4sfCAoYgWLXE9A90GLMVgFa5EuTS3paZ/tH3B/hvil9QQw/miqz+UXB/fStruVdeylshzyzKUVdvsD0JbG8DV4RuTw979dL7cgl1CPLTKH7wVLBKAe6SrgM2uBfjtvPjuHFEv+cBO9G1urnPJLs5665zp9rbkbdn3emYKB+tmZv8SphqQUQhmBsgVEmpskSCVQiSv/ZrndWVIkJYXbhgLXPAsD3DW+GKHcc+3LMa2zdO1j+2pI0QTRq94+JpEXTGdmNYstf/MSU=
  app: screwdriver-api-heroku
