language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install codecov
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: EDPxQw2fTLhf6Bbifjsj7c3bbwAZR56ZhGtZko/mS0IYTOMc8K0TzoCBJc25YT+jfN8sX1PFVUgkLPoeOPR6XTw+danPe49hyAutE77pjTLsGvz92G4a81+2o+qCnvL2rPsDKxNK5CbG2udNchls7YRVTNrWuvVTzmRKPsHqvaMtxUOVn96kV4wZoNW/XF1mGu5w5d6XXBU049LU6rGrajVGo7cQoQnfs28YEyf4u9QRjWo/aFpTFE5P6n2YZv3paQuVLh51bt4gxW1OuL0vGmYBj9ercQSzACPrwXip05FXmwUQXQJD8toMABNj5FEKWxJu3L4yyxnylwPr56LYELEa9WlPsKDzMee4/eUnvyKh2y4xMIaTVR+7Sv64WvzxJRMLfXqrK4OoK2iT8T9I7frXcHrpz2vmy/HfEmkFiXB+G4YZfnmvPz2WTcHl9CvurUBKkgyu4M3+Y4t+VnflQLozfSEU7xIwpuaZZ9UV9uIBKj19N7TF/gk9dZS93J2wFzpmwPwNc8pMdpKPUxGrdspzxRCCE251n99nRlKBrfJZNSK0Ks2qg3j3NLbqEJib8amXzrVOBbjhGoj755WmLSBVrXS8bTVaY8SoPG4zTMlFejGcMLTLPUcVNb523qLD8opXj5/NxRReCt9Nk9oQZtiM+F7ykfvqA0ajolVPM9o=
  app: screwdriver-api-heroku