language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install codecov
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: rN6apb07Qcn7611ooUDAoh+HGDZNE2Qzg9Ssvs3kAMEPqPa+Q6L51jasOaUMw8/uQfKl8kfkU6+gND01jfE1cqipeft2c7gwkhXnGhI5VLJLDY/6vKkYE3MgG4xYbLJvtjAvarUO9PO8k3fwF+mOKpuGpB7x3lpchAAwmxRJxXZ9F7x/5VCVgPu8MijAqL1WbFQmBlwt0uoYE701gpJfLf3wZfTYX1sl5N/MP/rjwbgPPy/nbjKMeehvlOKmNeMRV8nh13AVOwLWpu85q5oho4xyxLJmPBTEkSx+rvkWKIMy5C2T1x0mgcbkpTS9WV4wtW3Yn+uZChF2VXZIAKAR/ZkD0YZtO/pYZWgMCYDdVqDJ4fSeliFNxoeCtqQclbsJMWmMU4X970r9HeJPo4t0y9c5ksCJ4vdsEk5H0n6o2RIhE0PtkgOU4XUcLn25FiVKcmLh+fvY3inbmERUqzvQLs4oW0dWjFjSG4b1QVSmlkRpNDkHHYhKsyJP1w2Zz9qMuYKNely6bSTYnxoFzRBMlXKEh5yS3RA0FbuHkuNzS81sAEyeNYbqLDiZwiqGTelcKU0yBWatsyB+xXHKvjOaZSRFgiwTbt10I2+D9b+sdVZ0D+VwvnHtfdeNX9KReUTBkPwcK4kgsEKHTAUo37VqOJI4ihrkjVwJASf/zPBidXI=
  app: screwdriver-api-heroku
