language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install codecov
script:
- python -m unittest discover
deploy:
- provider: heroku
  api_key:
    secure: "Hs0y0hjqfH17MUKm4iP6gXSFXxTKhDA8/Q3WsqIx2ITXu+koNQhNGyJtwDHnldkq9fELnDQM/+iqn0LeWsOvMuU0N05PNnO76HIMzXfbUy2lBOZqcVPj9wx+/pdQbXpSaMCzi85B57/Oo7eEaV1t1A3A8Bt1oJDe2vtElBC7HTjyMzJruGhEO403sJRELF3FqV4vpm7DOt4eENYb0B/albqJmi0dRYoCSrzVOqasUvT1kk5ALHpgSka3DpchTZ+IYikSVllHUa28tIoLMDYp6hgV5lGHsOXiwzogc+64rVVKkeqL7Jfnj01BEfgha/mKVgjYt/y6cXj6yS+mBeRaP9LT29ujKJQIBOHg0YlvNqfWbZwChCSxottPKP17d0PvbVFv0FDuPHj9ODkxyeVW0aKoPz8nxLyEb+/LKGiCbc5A0z4x23dzImCVkw2mSes75sLUregH2xvzKGH8UTs45NnyNS23Eo4LF8V5ZlpG6yu16RG5GSAnlWNW8A56eY7H067znyQ1XoOrGPz+1m8K+XVwhMeff6UmcSybjixDqt/jSYMQW8zYFYNEwwG3f0uy/46b4VfS8QPfPAJ7hu3tWDMjSo6mtwq7KO7/U7cSfZ/sw/Wok+sH2hizXrE53JoyvVbj9ILn3k5nHFoz26QHtPIq4W9Yvz2+b4aa+BP28Ek="
  app: screwdriver-api-heroku
