language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install codecov
script:
- python -m unittest discover
deploy:
- provider: heroku
  api_key:
    secure: "Jj9QlTW2kOCjGhNTLwlKBUOe8AU1DahAoqIJByUBaduk76pZgbGcfuGwh+1rVjNnVdlw1X3RZo8QWJfF66gstEyvnTNDZwSctzUKcMiU1Y/lkF8b6HmahqX8FsIMAHhj57yEhtlvpuzjKG8SuY9q4E2eGXAZtOgoa1nOn7vGTgOlDt4swcqTEtZbe5reRG4aEIEANomnzZqwvm636rFFv+toi+OlNE3IfIEvxT5opFIJ5HQb6R9b9vUzWDJwXpaPcXhWpe0KwNvLJN3RvXefwotgcb7kpUvOXr1fDEqFyH7OqrkYxk8i2WL6S3i0aCQJIDTzYA/K9Mnkoo0lkRv+qNNpPk/zLfPnzN7MQusiK0PUjnEbIKQ57kBfXPNtCByLcHjR09Rq1/GxxXcAzBZ75LblCULpaLSwJPZWSM+K0TMdJ4+upQVYbvAdXVwSUITZPh5cYykq3MuqzLQsyKue6cC+7VT5JzspBGTFQFDHYGWE6biqKOOw7PJcOkMsjC0bmyticrh/f9ntUfGd1e4ImnN+2cP2sr6XzSJrFkqDJnlw04Gpttk8v/lL/8nGQzClnoMY7T13NrqWtnCIV3ObcJPTFUZT7Y6eXjVo29z+RSRug8C8OFXxoU8OuTBgbzhPu3a18iyXJ1IwsU+4TWiPWDDUqnLL97WwkOhXDu6aSaI="
  app: screwdriver-api-heroku
