language: python
python:
- 3.5
- 3.6
install:
- pip install -r requirements.txt
- pip install codecov
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: ejWGZscKtQbcmgS0JtxdLgVo930tWTw+qewtVGMxEgdnAzQVurWoyzoi1jdaeYDchOW6zJVhOQxnl523kJSr5qMG+qtohXTpxYQwOGE32vGMqloO5tkDHt6wq5ka5WJFqR1GqzY9/0GjdncBcfVav3vozUf1uO/eJcj8VIgV6DSZMEqHHTUaoADEs9f10+Ra/bdpzQri1oGLCQjs74lWl7AmhDX7qAjU2QgkKGn8LlnPvmuEq0tfPWcmGF4he/tNJ+fiqncDxla6fDw6iu5oh2sbEde2+WSqsfLPezO/YwctT0jbMPW5APXb3+O5E0ochcZLPuvY31Q/upZfnjQJISSxkMiivisPm1skxKsLRst5Pu77VN15LsfDEg2IOFf/dlQ6Yoh04Rtd7zjDTVZq4o3EmyWlHpsdBwG+zVyvQx930seVXovxKQSVGA5UwTqJsFjvB/5lvTJW1WXdkb47C6nL2nIqNDzqGBkyTKrpGh3kBAcn3F0BDdUqT29DRQSHcjGrtykplRw4S6boR6X8tZ4W6zi9JTraTmnYl09jvLW3ekpuVfVFBa9OaMXjWiPPqC8REH+X8R860Js06UuuzQFiwVw1oxv7nc+/1N/be4EkUmaW8ZpTLcKmDFvqOQykyOBQEyCTacXQzDY7Ok7H4gs8nywG7cY6MekxN2vQf5A=
  app: screwdriver-api-heroku
